server:
    port: 8080
spring:
    devtools:
        livereload:
            enabled: true
    application:
        name: user-service
    datasource:
        url: jdbc:mysql://mysql:3306/workshop-back
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: none
api:
    base-path: /api/v1